{
  "repos": [
  {
    "repo": "https://github.com/ambv/black",
    "rev": "stable",
    "hooks": [
    {
      "id": "black",
      "language_version": "python3.7"
    }
    ]
  },
  {
    "repo": "https://github.com/timothycrosley/isort",
    "rev": "4.3.21-2",
    "hooks": [
    {
      "id": "isort",
      "language": "python_venv",
      "language_version": "python3",
      "files": "^(src/.*\\.py|tests/.*\\.py)",
      "additional_dependencies": [
        "toml"
      ]
    }
    ]
  }
  ]
}
