repos:
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
    language_version: python3.7
- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21
  hooks:
  - id: isort
    language: python_venv
    language_version: python3
    files: "^(src/.*\\.py|tests/.*\\.py)"
    additional_dependencies:
    - toml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.770'
    hooks:
    -   id: mypy
