[tool.poetry]
name = "aapns"
version = "19.9"
description = "Asynchronous Apple Push Notification Service Client"
authors = ["Jonas Obrist <jonas.obrist@hennge.com>"]
license = "Apache-2.0"
repository = "https://github.com/hennge/aapns"
classifiers = [
  "Development Status :: 4 - Beta",
  "Framework :: AsyncIO",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3 :: Only",
]

[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.7.2"
attrs = "^19.1.0"
structlog = "^19.1.0"
click = {version = "^7.0", extras = ["cli"]}

[tool.poetry.dev-dependencies]
pytest = "^3.0"
cryptography = "^2.7"
pytest-asyncio = "^0.10.0"
sphinx = "^2.2.0"
mypy = "^0.720"

[tool.poetry.scripts]
aapns = "aapns.cli:main"

[tool.isort]
line_length = "88"
multi_line_output = "3"
combine_as_imports = "1"
include_trailing_comma = "True"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
