version: 2
jobs:
  build:
    docker:
      - image: ojii/aapns:latest
    working_directory: /home/
    steps:
      - checkout
      - run: /virtualenv/bin/pip install . -r tests/requirements.txt
      - run: /virtualenv/bin/pytest --verbose
