version: 2
jobs:
  build:
    docker:
      - image: ojii/aapns:latest
    working_directory: /home/
    steps:
      - checkout
      - run: /virtualenv/bin/pip install . -r tests/requirements.txt
      - run: /virtualenv/bin/pytest --verbose --junitxml=reports/results/junit.xml --cov=aapns --cov-report=html:reports/coverage/
      - store_test_results:
          path: reports/results/
      - store_artifacts:
          path: reports/coverage/
          destination: reports
